shinyUI(fluidPage(
        titlePanel("Probabilistic Business Case Tweaker"),
        p("This app aims to help you work with business cases where there is a lot of uncertainty.  It assumes normal distributions of benfits and costs and uses a Monte Carlo Simulation to caculate a resulting profit.  It then allows you to compare your baseline business case to one where you tweak some of your input parameter."),
        br(),
        fluidRow(
                column(4,
                  h4("Benefits:"),
                  p("Enter the revenue generated by your project here, with your upper
                    and lower bounds representing the upper and lower limit to your 
                    90% confidence interval.  Note that in this version, you upper bound should be higher than your lower bound.")),
                column(4,
                       h4("Capital Costs:"),
                       p("Enter the capital costs for your project here, with your upper
                    and lower bounds representing the upper and lower limit to your 
                    90% confidence interval.  Note that in this version, you upper bound should be higher than your lower bound.")),
                column(4,
                       h4("Operational Costs:"),
                       p("Enter the Operational costs for your project here, with your upper
                    and lower bounds representing the upper and lower limit to your 
                    90% confidence interval. Note that in this version, you upper bound should be higher than your lower bound."))
        ),
        fluidRow(
                column(4,
                       numericInput(inputId="benefit.upper", label = h4("Benefit - Upper Bound"), value=0)),
                column(4,
                       numericInput(inputId="capex.upper", label = h4("Capex - Upper Bound"),value=0)),
                column(4,
                       numericInput(inputId="opex.upper", label = h4("Opex - Upper Bound"),value=0))
        ),
        fluidRow(
                column(4,
                       numericInput(inputId="benefit.lower", label = h4("Benefit - Lower Bound"),value=0)),
                column(4,
                       numericInput(inputId="capex.lower", label = h4("Capex - Lower Bound"),value=0)),
                column(4,
                       numericInput(inputId="opex.lower", label = h4("Opex - Lower Bound"),value=0))
        ),
        fluidRow(
                column(4,
                       p("These boxes modify your right hand business case - helping you choose what values you should focus on if you want your idea to work better."),
                       checkboxGroupInput("benefits.check", label = h4("Parameters"), 
                                          choices = list("Halve Uncertainty" = 1, "Increase by 20%" = 2))),
                column(4,
                       p("These boxes modify your right hand business case - helping you choose what values you should focus on if you want your idea to work better."),
                       checkboxGroupInput("capex.check", label = h4("Parameters"), 
                                          choices = list("Halve Uncertainty" = 1, "Decrease by 20%" = 2))),
                column(4,
                       p("These boxes modify your right hand business case - helping you choose what values you should focus on if you want your idea to work better."),
                       checkboxGroupInput("opex.check", label = h4("Parameters"), 
                                          choices = list("Halve Uncertainty" = 1, "Decrease by 20%" = 2)))
        ),
        fluidRow(
                column(6,
                       plotOutput('plot'),
                       p("This graph shows a Monte Carlo simulation of the baseline business case values entered.  The blue line represents your mean profit and the red lines your upper and lower bounds to your 90th percentile confidence interval.")),
                column(6,
                       plotOutput('plot2'),
                       p("This graph shows a Monte Carlo simulation of the modified business case, which takes into account the check boxes selected.  The blue line represents your mean profit and the red lines your upper and lower bounds to your 90th percentile confidence interval."))
        )
))